#!/bin/bash

[[ $(( "$#" - 2 )) -ne 0 ]] && echo "call this script with exactly two ips the 'from ip' and the 'to ip' in increasing order" && exit -1;

f_call="$0_fun"; #script to call each time
ip1="$1"; #from ip
ip2="$2"; #to ip

# valid ip
[[ $(echo $ip1 | sed 's/\./\n/g' | wc -l) -ne 4 ]] && echo "invalid ip: $ip1" && exit -1;
[[ $(echo $ip2 | sed 's/\./\n/g' | wc -l) -ne 4 ]] && echo "invalid ip: $ip2" && exit -1;

for i in $(echo $ip1 | sed 's/\./ /g' ); do
	[[ $i -lt 0 || $i -gt 255 ]] && (echo "invalid range $i" && exit -1);
done;

for i in $(echo $ip2 | sed 's/\./ /g' ); do
	[[ $i -lt 0 || $i -gt 255 ]] && (echo "invalid range $i" && exit -1);
done;

#range check, from_ip should be small or equal
a=$(( "$(echo $ip1 | cut -d. -f1)" - "$(echo $ip2 | cut -d. -f1)" ));
if [[ $a -gt 0 ]]; then
	echo "invalid range";
	exit -1;
elif [[ $a -eq 0 ]]; then
	b=$(( "$(echo $ip1 | cut -d. -f2)" - "$(echo $ip2 | cut -d. -f2)" ));	
	if [[ $b -gt 0 ]]; then
		echo "invalid range";
		exit -1;
	elif [[ $b -eq  0 ]]; then
		c=$(( "$(echo $ip1 | cut -d. -f3)" - "$(echo $ip2 | cut -d. -f3)" ));
		if [[ $c -gt 0 ]]; then
			echo "invalid range";
			exit -1;
		elif [[ $c -eq 0 ]]; then
			d=$(( "$(echo $ip1 | cut -d. -f4)" - "$(echo $ip2 | cut -d. -f4)" ));
			if [[ $d -gt 0 ]]; then
			       echo "invalid range";
			       exit -1;
			fi;
		fi;
	fi;
fi;

#process, include:from_ip, exclude: to_ip
while [[ "$ip1" != "$ip2" ]]; do
	source $f_call $ip1;   #ip is passed to other file for process
	#calc next ip
	a="$( echo $ip1 | cut -d. -f1)";
	b="$( echo $ip1 | cut -d. -f2)";
	c="$( echo $ip1 | cut -d. -f3)";
	d="$( echo $ip1 | cut -d. -f4)";

	if [[ $d -lt 255 ]]; then
		d="$(( $d + 1 ))";
	else
		d=0;
		if [[ $c -lt 255 ]]; then
			c="$(( $c + 1 ))";
		else
			c=0;
			if [[ $b -lt 255 ]]; then
				b="$(( $b + 1 ))";
			else
				b=0;
				if [[ $a -lt 255 ]]; then
					a="$(( $a + 1 ))";
				else
					break;
				fi;
			fi;
		fi;
	fi;
	ip1="$a.$b.$c.$d";
done;
echo "done"
